# Generated by Django 3.1.2 on 2020-10-09 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0007_sqlquery_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='num_api_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('json_data', models.TextField(default=None, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('identifier', models.IntegerField(default=-1)),
                ('traceback', models.TextField()),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='silk.request')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='api_calls',
            field=models.ManyToManyField(db_index=True, related_name='profiles_api_calls', to='silk.APICall'),
        ),
    ]
